workload:
  model: unet3d
  framework: pytorch
  workflow:
    generate_data: true
    train: false
    checkpoint: true
    profiling: false
  dataset:
    data_folder: /mnt/mltest/unet3d_data
    format: npz
    num_files_train: 1396500
    num_samples_per_file: 1
    record_length: 146600628
    record_length_stdev: 68341808
    record_length_resize: 2097152
    num_subfolders_train: 48
  reader:
    data_loader: pytorch
    batch_size: 7
    read_threads: 4
    file_shuffle: seed
    sample_shuffle: seed
  train:
    epochs: 5
    computation_time: 0.323
  checkpoint:
    checkpoint_folder: checkpoints/unet3d
    checkpoint_after_epoch: 5
    epochs_between_checkpoints: 2
    model_size: 499153191
  metric:
    au: 0.9
  profiling:
    profiler: none
